version: '3.9'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    container_name: music_service
    volumes:
      - .:/FCMusic
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:14.3
    volumes:
      - postgres_data:/var/lib/postgres/data/
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fcmusic_db

volumes:
  postgres_data:
